### PR TITLE
allows you to use it as a module instead of a hapi plugin

### PR DESCRIPTION
**Pull request by orthagonal**
tests updated to accomodate

### CODE REVIEW

**Comment by orthagonal** [comment]
@jgallen23 needs to review and merge this guy

**Comment by jgallen23** [comment]
same issues as hapi-method-loader.  Should still work as hapi plugin

**Comment by orthagonal** [comment]
now supports both register and manual usage
includes tests for both scenarios
check it out @jgallen23

**Comment by jgallen23** [comment]
lets add linting like hapi-method-loader and then make sure all of those errors are fixed

**Pull request closed without merging**
